name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux-amd64
            runs-on: ubuntu-24.04
          - platform: linux-arm64
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.runs-on }}

    outputs:
      commit_hash: ${{ steps.gitinfo.outputs.COMMIT_HASH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to set the REVISION

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get metadata
        id: gitinfo
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "REVISION=$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./cmd/kubeacme/Dockerfile
          build-args: |
            COMMIT_HASH=${{ steps.gitinfo.outputs.COMMIT_HASH }}
            REVISION=${{ steps.gitinfo.outputs.REVISION }}
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/kube-acme:${{ steps.gitinfo.outputs.COMMIT_HASH }}-${{ matrix.platform }}

  manifest:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest
        run: |
          docker manifest create ${{ vars.DOCKERHUB_USERNAME }}/kube-acme:latest \
            --amend ${{ vars.DOCKERHUB_USERNAME }}/kube-acme:${{ needs.build.outputs.commit_hash }}-linux-amd64 \
            --amend ${{ vars.DOCKERHUB_USERNAME }}/kube-acme:${{ needs.build.outputs.commit_hash }}-linux-arm64
          docker manifest push ${{ vars.DOCKERHUB_USERNAME }}/kube-acme:latest
